SELECT distinct cast(nullif(date,'') as timestamp) as date,
cast(nullif(time,'') as time) as time,
system_setting,
system_mode,
calendar_event,
program_mode,
cast(nullif(cool_set_temp,'') as double) as cool_set_temp,
cast(nullif(heat_set_temp,'') as double) as heat_set_temp,
cast(nullif(current_temp,'') as double) as current_temp,
cast(nullif(current_humidity,'') as double) as current_humidity,
cast(nullif(outdoor_temp,'') as double) as outdoor_temp,
cast(nullif(outdoor_wind_speed,'') as double) as outdoor_wind_speed,
cast(nullif(cool_stage1_seconds,'') as double) as cool_stage1_seconds,
cast(nullif(heat_stage1_seconds,'') as double) as heat_stage1_seconds,
cast(nullif(fan_seconds,'') as double) as fan_seconds,
dm_offset,
cast(nullif(thermostat_temp,'') as double) as thermostat_temp,
cast(nullif(thermostat_humidity,'') as double) as thermostat_humidity,
cast(nullif(thermostat_motion,'') as double) as thermostat_motion,
cast(nullif(sensor1_temp,'') as double) as sensor1_temp,
cast(nullif(sensor1_motion,'') as double) as sensor1_motion,
cast(nullif(sensor2_temp,'') as double) as sensor2_temp,
cast(nullif(sensor2_motion,'') as double) as sensor2_motion,
cast(nullif(sensor3_temp,'') as double) as sensor3_temp,
cast(nullif(sensor3_motion,'') as double) as sensor3_motion
FROM thermostat_insights_prd.observation
order by date, time desc