Select
    date,
    min(time) as time,
    max(system_setting) as system_setting,
    max(system_mode) as system_mode,
    max(calendar_event) as calendar_event,
    max(program_mode) as program_mode,
    min(cool_set_temp) as cool_set_temp,
    max(heat_set_temp) as heat_set_temp,
    max(current_temp) as current_temp,
    max(current_humidity) as current_humidity,
    max(outdoor_temp) as outdoor_temp,
    max(outdoor_wind_speed) as outdoor_wind_speed,
    sum(cool_stage1_seconds) as cool_stage1_seconds,
    sum(heat_stage1_seconds) as heat_stage1_seconds,
    sum(fan_seconds) as fan_seconds,
    max(dm_offset) as dm_offset,
    max(thermostat_temp) as thermostat_temp,
    max(thermostat_humidity) as thermostat_humidity,
    sum(thermostat_motion) as thermostat_motion,
    max(sensor1_temp) as sensor1_temp,
    sum(sensor1_motion) as sensor1_motion,
    max(sensor2_temp) as sensor2_temp,
    sum(sensor2_motion) as sensor2_motion,
    max(sensor3_temp) as sensor3_temp,
    sum(sensor3_motion) as sensor3_motion
from
(
    SELECT distinct cast(nullif(date,'') as timestamp) as date,
    cast(nullif(time,'') as time) as time,
    extract(hour from cast(nullif(time,'') as time)) as hour,
    system_setting,
    system_mode,
    calendar_event,
    program_mode,
    cast(nullif(cool_set_temp,'') as double) as cool_set_temp,
    cast(nullif(heat_set_temp,'') as double) as heat_set_temp,
    cast(nullif(current_temp,'') as double) as current_temp,
    cast(nullif(current_humidity,'') as double) as current_humidity,
    cast(nullif(outdoor_temp,'') as double) as outdoor_temp,
    cast(nullif(outdoor_wind_speed,'') as double) as outdoor_wind_speed,
    cast(nullif(cool_stage1_seconds,'') as double) as cool_stage1_seconds,
    cast(nullif(heat_stage1_seconds,'') as double) as heat_stage1_seconds,
    cast(nullif(fan_seconds,'') as double) as fan_seconds,
    dm_offset,
    cast(nullif(thermostat_temp,'') as double) as thermostat_temp,
    cast(nullif(thermostat_humidity,'') as double) as thermostat_humidity,
    cast(nullif(thermostat_motion,'') as double) as thermostat_motion,
    cast(nullif(sensor1_temp,'') as double) as sensor1_temp,
    cast(nullif(sensor1_motion,'') as double) as sensor1_motion,
    cast(nullif(sensor2_temp,'') as double) as sensor2_temp,
    cast(nullif(sensor2_motion,'') as double) as sensor2_motion,
    cast(nullif(sensor3_temp,'') as double) as sensor3_temp,
    cast(nullif(sensor3_motion,'') as double) as sensor3_motion
    FROM thermostat_insights_prd.observation
)
group by date, hour
order by date desc, time desc